config/routes.rb
Rails.application.routes.draw do
  root to: 'mortgages#index'
  devise_for :users
  
  resources :mortgages, shallow: true do
    resources :conditions, only: [:create, :update, :destroy, :edit]
  end

  resources :calculations, only: [:create, :show, :new, :index]
end

app/models/condition.rb
class Condition < ApplicationRecord
  belongs_to :mortgage

  validates :interest_rate, :value_max_loan_amount, presence: true
  validate :validate_value_interest_rate

  private

  def validate_value_interest_rate
    count = 0
    Condition.attribute_names.each do |name_attribute|
      if name_attribute.include?('value_interest_rate') && send(name_attribute) != nil
        count += 1
        break
      end
    end

    if count == 0
      errors.add(:interest_rate, I18n.t('flash.conditions.value_interest_rate'))
    end
  end
end

app/controllers/conditions_controller.rb
class ConditionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  authorize_resource
  
  before_action :set_mortgage, only: [:create]
  before_action :load_condition, only: [:destroy, :update, :edit]
  
  def create
    @condition = @mortgage.build_condition(condition_params)
    if @condition.save
      redirect_to @mortgage, notice: t('flash.conditions.create', title: @mortgage.title)
    else
      render 'mortgages/show', status: :unprocessable_entity
    end
  end

  def edit
  end
  
  def update
    if @condition.update(condition_params)
      redirect_to @condition.mortgage, notice: t('flash.conditions.edit', title: @condition.mortgage.title)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @mortgage = @condition.mortgage
    @condition.destroy
    redirect_to @mortgage, status: :see_other, notice: t('flash.conditions.delete', title: @mortgage.title)
  end

  private
  def set_mortgage
    @mortgage = Mortgage.find(params[:mortgage_id])
  end

  def load_condition
    @condition = Condition.find(params[:id])
  end

  def condition_params
    params.require(:condition).permit(:interest_rate, 
                                      :max_loan_amount,
                                      :max_loan_term,
                                      :max_age,
                                      :income,
                                      :note,
                                      :an_initial_fee,
                                      :experience_and_registration,
                                      :type_of_housing,
                                      :value_interest_rate_with_commision,
                                      :value_interest_rate_without_commision,
                                      :value_interest_rate_with_proof_of_income,
                                      :value_interest_rate_without_proof_of_income,
                                      :value_interest_rate_with_commision_with_proof_of_income,
                                      :value_interest_rate_with_commision_without_proof_of_income,
                                      :value_interest_rate_without_commision_with_proof_of_income,
                                      :value_interest_rate_without_commision_without_proof_of_income,
                                      :value_interest_rate_for_payroll_project,
                                      :value_max_loan_amount,
                                      :value_max_loan_term,
                                      :value_max_age,
                                      :value_min_an_initial_fee,
                                      :value_max_an_initial_fee,
                                      :value_income,
                                      :value_loan_processing_fee,
                                      :value_application_fee,
                                      :value_arly_redemption_fee,
                                      :additional_expenses,
                                      :value_additional_expenses,
                                      :pledge,
                                      :insurance,
                                      :value_insurance)
  end
end

app/helpers/conditions_helper.rb
module ConditionsHelper
end

app/views/conditions/_condition.html.slim
div class='mortgage-condition d-flex flex-column'
  div class='d-flex justify-content-end mt-2'
    = link_to t('mortgages.common.calculate'), new_calculation_path(page: "mortgage-#{@mortgage.id}"), class: 'btn btn-secondary mx-2'
    = link_to t('mortgages.common.main'), mortgages_path ,class: 'btn btn-secondary'   
    - if can?(:edit, Condition)
      = link_to t('mortgages.show.edit_condition'), edit_condition_path(condition),  class: 'btn btn-secondary mx-2'
      = link_to t('mortgages.show.delete_condition'), condition_path(condition), data: { turbo_confirm: t('conditions.delete.confirm'), turbo_method: :delete },  class: 'btn btn-secondary'

  div class='condition-interest-rate border mt-2'
    div class='condition-description-interest-rate d-flex flex-row w-100 shadow'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.interest_rate')
      div class='content-field w-75 px-3 '  
        p= condition.interest_rate
    div class='condition-value-interest-rate d-flex flex-wrap justify-content-center w-100 mt-2'
      - if condition.value_interest_rate_with_commision  
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_with_commision')
          div class='content-field'
            p= condition.value_interest_rate_with_commision
      - if condition.value_interest_rate_without_commision
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_without_commision')
          div class='content-field'
            p= condition.value_interest_rate_without_commision
      - if condition.value_interest_rate_with_proof_of_income
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_with_proof_of_income')
          div class='content-field'
            p= condition.value_interest_rate_with_proof_of_income
      - if condition.value_interest_rate_without_proof_of_income
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_without_proof_of_income')
          div class='content-field'
            p= condition.value_interest_rate_without_proof_of_income
      - if condition.value_interest_rate_with_commision_with_proof_of_income
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_with_commision_with_proof_of_income')
          div class='content-field'
            p= condition.value_interest_rate_with_commision_with_proof_of_income
      - if condition.value_interest_rate_with_commision_without_proof_of_income
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_with_commision_without_proof_of_income')
          div class='content-field'
            p= condition.value_interest_rate_with_commision_without_proof_of_income
      - if condition.value_interest_rate_without_commision_with_proof_of_income
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_without_commision_with_proof_of_income')
          div class='content-field'
            p= condition.value_interest_rate_without_commision_with_proof_of_income
      - if condition.value_interest_rate_without_commision_without_proof_of_income
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_without_commision_without_proof_of_income')
          div class='content-field'
            p= condition.value_interest_rate_without_commision_without_proof_of_income
      - if condition.value_interest_rate_for_payroll_project
        div class='d-flex flex-column text-center shadow m-2 p-1'
          div class='title-field'
            p= t('mortgages.show.value_interest_rate_for_payroll_project')
          div class='content-field'
            p= condition.value_interest_rate_for_payroll_project
  div class='condition-max-loan-amount mt-2'
    - if condition.max_loan_amount && !condition.max_loan_amount.blank?     
      div class='condition-max-loan-amount d-flex flex-row w-100'
        div class='title-field w-25 px-3'
          p= t('mortgages.show.max_loan_amount')
        div class='content-field w-75 px-3'  
          p= condition.max_loan_amount
    div class='condition-value-max-loan-amount d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_max_loan_amount')
      div class='content-field w-75 px-3'  
        p= condition.value_max_loan_amount
  - if condition.max_loan_term && !condition.max_loan_term.blank?
    div class='condition-max-loan-term d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.max_loan_term')
      div class='content-field w-75 px-3' 
        p= condition.max_loan_term
  - if condition.value_max_loan_term
    div class='condition-value-max-loan-term d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_max_loan_term')
      div class='content-field w-75 px-3' 
        p= condition.value_max_loan_term
  - if condition.max_age && !condition.max_age.blank?
    div class='condition-max-age d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.max_age')
      div class='content-field w-75 px-3' 
        p= condition.max_age
  - if condition.value_max_age
    div class='condition-value-max-age d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_max_age')
      div class='content-field w-75 px-3' 
        p= condition.value_max_age
  - if condition.income && !condition.income.blank?  
    div class='condition-income d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.income')
      div class='content-field w-75 px-3' 
        p= condition.income
  - if condition.value_income 
    div class='condition-value-income d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_income')
      div class='content-field w-75 px-3' 
        p= condition.value_income
  - if condition.an_initial_fee && !condition.an_initial_fee.blank? 
    div class='condition-an-initial-fee d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.an_initial_fee')
      div class='content-field w-75 px-3'     
        p= condition.an_initial_fee
  - if condition.value_min_an_initial_fee
    div class='condition-value-min-an-initial-fee d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_min_an_initial_fee')
      div class='content-field w-75 px-3'     
        p= condition.value_min_an_initial_fee
  - if condition.value_max_an_initial_fee
    div class='condition-value-max-an-initial-fee d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_max_an_initial_fee')
      div class='content-field w-75 px-3'     
        p= condition.value_max_an_initial_fee
  - if condition.additional_expenses && !condition.additional_expenses.blank?
    div class='condition-additional-expenses d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.additional_expenses')
      div class='content-field w-75 px-3'     
        p= condition.additional_expenses    
  - if condition.value_additional_expenses
    div class='condition-value-additional-expenses d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_additional_expenses')
      div class='content-field w-75 px-3'     
        p= condition.value_additional_expenses 
  - if condition.value_loan_processing_fee
    div class='condition-value-loan-processing-fee d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_loan_processing_fee')
      div class='content-field w-75 px-3'     
        p= condition.value_loan_processing_fee
  - if condition.value_application_fee
    div class='condition-value-application-fee d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_application_fee')
      div class='content-field w-75 px-3'     
        p= condition.value_application_fee    
  - if condition.value_arly_redemption_fee
    div class='condition-value-arly-redemption-fee d-flex flex-row w-100 mt-2'
      div class='title-field w-25 px-3'
        p=  t('mortgages.show.value_arly_redemption_fee')
      div class='content-field w-75 px-3'     
        p= condition.value_arly_redemption_fee   
  - if condition.pledge && !condition.pledge.blank? 
    div class='condition-pledge d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.pledge')
      div class='value w-75 px-3'     
        p= condition.pledge
  - if condition.insurance && !condition.insurance.blank? 
    div class='condition-insurance d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.insurance')
      div class='value w-75 px-3'     
        p= condition.insurance
  - if condition.value_insurance && !condition.value_insurance.blank? 
    div class='condition-value-insurance d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.value_insurance')
      div class='value w-75 px-3'     
        p= condition.value_insurance
  - if condition.experience_and_registration && !condition.experience_and_registration.blank? 
    div class='condition-experience-and-registration d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.experience_and_registration')
      div class='value w-75 px-3'     
        p= condition.experience_and_registration
  - if condition.type_of_housing && !condition.type_of_housing.blank? 
    div class='condition-type-of-housing d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.type_of_housing')
      div class='value w-75 px-3'     
        p= condition.type_of_housing
  - if condition.note && !condition.note.blank? 
    div class='condition-note d-flex flex-row w-100'
      div class='title-field w-25 px-3'
        p= t('mortgages.show.note')
      div class='value w-75 px-3'     
        p= condition.note

app/views/conditions/_form.html.slim
div
  = render 'shared/errors', resource: @condition

  = form_with model: [@mortgage, @condition], class: 'form-group' do |f|
    div class='border p-2 mt-2 d-flex flex-column'
      div class='p-2'
        = f.label :interest_rate
        = f.text_field :interest_rate, class: 'form-control', placeholder: 'String'
      div class='d-flex flex-row flex-wrap'
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_with_commision 
          = f.text_field :value_interest_rate_with_commision, class: 'form-control', placeholder: 'Float'    
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_without_commision
          = f.text_field :value_interest_rate_without_commision, class: 'form-control', placeholder: 'Float'  
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_with_proof_of_income 
          = f.text_field :value_interest_rate_with_proof_of_income, class: 'form-control', placeholder: 'Float'
        div class='w-50 text-center p-2'  
          = f.label :value_interest_rate_without_proof_of_income
          = f.text_field :value_interest_rate_without_proof_of_income, class: 'form-control', placeholder: 'Float'  
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_with_commision_with_proof_of_income 
          = f.text_field :value_interest_rate_with_commision_with_proof_of_income, class: 'form-control', placeholder: 'Float'
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_with_commision_without_proof_of_income 
          = f.text_field :value_interest_rate_with_commision_without_proof_of_income, class: 'form-control', placeholder: 'Float'   
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_without_commision_with_proof_of_income 
          = f.text_field :value_interest_rate_without_commision_with_proof_of_income, class: 'form-control', placeholder: 'Float'  
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_without_commision_without_proof_of_income
          = f.text_field :value_interest_rate_without_commision_without_proof_of_income, class: 'form-control', placeholder: 'Float'  
        div class='w-50 text-center p-2'
          = f.label :value_interest_rate_for_payroll_project
          = f.text_field :value_interest_rate_for_payroll_project, class: 'form-control', placeholder: 'Float'  

    div class='d-flex flex-row'
      div class='text-center p-2 w-75'
        = f.label :max_loan_amount
        = f.text_field :max_loan_amount, class: 'form-control', placeholder: 'String'
      div class='text-center p-2 w-25'
        = f.label :value_max_loan_amount
        = f.text_field :value_max_loan_amount, class: 'form-control', placeholder: 'Integer'
    div class='d-flex flex-row'
      div class='text-center p-2 w-75'
        = f.label :max_loan_term 
        = f.text_field :max_loan_term, class: 'form-control', placeholder: 'String'
      div class='text-center p-2 w-25'
        = f.label :value_max_loan_term 
        = f.text_field :value_max_loan_term, class: 'form-control', placeholder: 'Integer'
    div class='d-flex flex-row'
      div class='text-center p-2 w-75'
        = f.label :max_age 
        = f.text_field :max_age, class: 'form-control', placeholder: 'String'
      div class='text-center p-2 w-25'
        = f.label :value_max_age 
        = f.text_field :value_max_age, class: 'form-control', placeholder: 'Integer'
    div class='d-flex flex-row'
      div class='text-center p-2 w-75'
        = f.label :income
        = f.text_area :income, class: 'form-control', placeholder: 'Text'
      div class='text-center p-2 w-25'
        = f.label :value_income
        = f.text_field :value_income, class: 'form-control', placeholder: 'Integer'

    div class='d-flex flex-row align-items-center'
      div class='w-75 p-2'
        = f.label :an_initial_fee 
        = f.text_field :an_initial_fee, class: 'form-control', placeholder: 'String'
      div class='w-25 d-flex flex-column'
        div class='text-center p-2'
          = f.label :value_min_an_initial_fee 
          = f.text_field :value_min_an_initial_fee, class: 'form-control', placeholder: 'Integer'
        div class='text-center p-2'
          = f.label :value_max_an_initial_fee 
          = f.text_field :value_max_an_initial_fee, class: 'form-control', placeholder: 'Integer'

    div class='d-flex flex-row'
      div class='text-center p-2 w-75'
        = f.label :additional_expenses
        = f.text_field :additional_expenses, class: 'form-control', placeholder: 'String'
      div class='text-center p-2 w-25'      
        = f.label :value_additional_expenses
        = f.text_field :value_additional_expenses, class: 'form-control', placeholder: 'Float'
    div class='d-flex flex-row text-center'
      div class='p-2 text-center w-50'
        = f.label :value_loan_processing_fee
        = f.text_field :value_loan_processing_fee, class: 'form-control', placeholder: 'Float'
      div class='p-2 text-center w-50'
        = f.label :value_application_fee
        = f.text_field :value_application_fee, class: 'form-control', placeholder: 'Float'
    div class='d-flex justify-content-center p-2'
      div class='w-50 text-center'
        = f.label :value_arly_redemption_fee
        = f.text_field :value_arly_redemption_fee, class: 'form-control', placeholder: 'Float'
    
    div class='p-2'
      = f.label :pledge
      = f.text_field :pledge, class: 'form-control', placeholder: 'String'

    div class='d-flex flex-row'
      div class='text-center p-2 w-75'
        = f.label :insurance
        = f.text_field :insurance, class: 'form-control', placeholder: 'String'
      div class='text-center p-2 w-25'      
        = f.label :value_insurance
        = f.text_field :value_insurance, class: 'form-control', placeholder: 'Float'   
    div class='p-2'
      = f.label :experience_and_registration
      = f.text_area :experience_and_registration, class: 'form-control', placeholder: 'Text'
    div class='p-2'
      = f.label :type_of_housing 
      = f.text_field :type_of_housing, class: 'form-control', placeholder: 'String'
    div class='p-2'
      = f.label :note
      = f.text_area :note, class: 'form-control', placeholder: 'Text'

    div class='p-2 d-flex justify-content-center'
      = f.submit t("conditions.edit.#{resource[2]}_condition".downcase), class: 'btn btn-primary w-25'

app/views/conditions/edit.html.slim
div class='edit-condition d-flex flex-column w-100 p-2 bg-light'
  div class='mortgage-title text-center border-bottom'
    h3= t('conditions.edit.title_page')+" #{@condition.mortgage.title}"
  div class='d-flex justify-content-end mt-2'
    = link_to t('mortgages.common.main'), mortgages_path ,class: 'btn btn-secondary' 
  - if can?(:edit, Condition)
    div
      = render 'form', resource: [@mortgage, @condition, 'Update']