config/routes.rb
Rails.application.routes.draw do
  root to: 'mortgages#index'
  devise_for :users
  
  resources :mortgages, shallow: true do
    resources :conditions, only: [:create, :update, :destroy, :edit]
  end

  resources :calculations, only: [:create, :show, :new, :index]
end

app/models/mortgage.rb
class Mortgage < ApplicationRecord
  enum :type_mortgage, [:commercial_bank, :state_programm, :otbasy_bank]
  has_one :condition, dependent: :destroy
  
  validates :title, :description, :type_mortgage, presence: true
  validate :validate_title_banks_partners

  private
  def validate_title_banks_partners
    if type_mortgage == 'commercial_bank' && (title_banks_partners.empty? || title_banks_partners.length > 1)
      errors.add(:title_banks_partners, I18n.t('flash.mortgages.commercial_bank') )
    elsif type_mortgage == 'state_programm' && title_banks_partners.empty? 
      errors.add(:title_banks_partners, I18n.t('flash.mortgages.state_programm') )
    elsif type_mortgage == 'otbasy_bank' && ( title_banks_partners.empty? || ( title_banks_partners.length > 1 || title_banks_partners.first != 'OtbasyBank' ))
      errors.add(:title_banks_partners, I18n.t('flash.mortgages.otbasy_bank') )
    end      
  end
end

app/controllers/mortgages_controller.rb
class MortgagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  authorize_resource

  before_action :load_mortgage, only: [:show, :edit, :update, :destroy]

  def index
    @mortgages = Mortgage.all
  end

  def show
    @condition = Condition.new
  end

  def new
    @mortgage = Mortgage.new
  end

  def edit
  end

  def create
    @mortgage = Mortgage.new(mortgage_params)
    
    if @mortgage.save
      redirect_to @mortgage, notice: t('flash.mortgages.create')    
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @mortgage.title_banks_partners.clear unless mortgage_params.include?(:title_banks_partners)
    if @mortgage.update(mortgage_params)
      redirect_to @mortgage, notice: t('flash.mortgages.edit', title: @mortgage.title)  
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @mortgage.destroy
    redirect_to mortgages_path, notice: t('flash.mortgages.delete', title: @mortgage.title) 
  end

  private
  def load_mortgage
    @mortgage = Mortgage.find(params[:id])
  end

  def mortgage_params
    params.require(:mortgage).permit(:title, 
                                     :description, 
                                     :type_mortgage, 
                                     title_banks_partners: [])
  end
end

app/helpers/mortgages_helper.rb
module MortgagesHelper
end

app/views/mortgages/_form.html.slim
= render 'shared/errors', resource: @mortgage

= form_with model: @mortgage, class: 'form-group' do |f|
  = f.label :title, Mortgage.human_attribute_name("title")
  = f.text_field :title, class: 'form-control'
  = f.label :description, Mortgage.human_attribute_name("description")
  = f.text_area :description, class: 'form-control'
  = f.collection_radio_buttons :type_mortgage, Mortgage.type_mortgages, :first, :first do |type|
    div class='form-check form-check-inline mt-2'
      - split_type_mortgage = type.label.delete_suffix("</label>").split(">") << "</label>"
      - localize_type_mortgage = Mortgage.human_attribute_name(split_type_mortgage.second)
      - split_type_mortgage.second.replace(localize_type_mortgage)
      - split_type_mortgage.insert(1, ">")  
      = type.radio_button class: 'form-check-input'
      = split_type_mortgage.join.html_safe
  br

  div class='border mt-2 p-2'
    div class='text-center'
      h5= t('mortgages.new.banks_partners')
    div
      = f.collection_check_boxes :title_banks_partners, 
                                 ['HalykBank', 'SberBank', 'KaspiBank', 'OtbasyBank',
                                  'First Heartland Jusan Bank', 'ForteBank', 'BankCenterCredit',
                                  'EurasianBank', 'BankRBK', 'CitiBank', 'Eco Center Bank',
                                  'AltynBank', 'VTB Bank', 'Home Credit Bank', 'HurBank',
                                  'Bank of China Limited', 'Bank Freedom Finance',
                                  'Industrial and Commercial Bank of China', 'KZI Bank',
                                  'Shinhan Bank', 'Al Hilal Bank', 'ZamanBank'], :itself, :itself, include_hidden: false do |b|
        div class='form-check form-check-inline mt-2'
          = b.label class: 'form-check-label'
          = b.check_box class: 'form-check-input'
    
  = f.submit t("mortgages.common.#{resource[1]}_mortgage".downcase), class: 'btn btn-primary mt-2'

                     

app/views/mortgages/_mortgage.html.slim
div id="mortgage-#{mortgage.id}" class='shadow d-flex flex-row my-2 p-1 border rounded bg-white'
  div class='mortgage-title text-center w-25'
    h3= mortgage.title
  div class='mortgage-description w-50 px-3'
    h5= mortgage.description
  div class='mortgage-action w-25 text-center d-flex flex-column justify-content-around'
    div
      = link_to t('mortgages.index.more'), mortgage_path(mortgage), class: 'link-action-mortgage'
    - if can?(:edit, mortgage)
      div
        = link_to t('mortgages.index.edit'), edit_mortgage_path(mortgage), class: 'link-action-mortgage'
    - if can?(:destroy, mortgage)  
      div
        = link_to t('mortgages.index.delete'), mortgage_path(mortgage), data: { turbo_confirm: t('mortgages.delete.confirm'), turbo_method: :delete }, class: 'link-action-mortgage'

app/views/mortgages/edit.html.slim
div class='update-mortgage w-100 bg-light p-2 d-flex flex-column'
  div class='text-center border-bottom'
    h2= t('mortgages.edit.title_page')
  div class='d-flex justify-content-end mt-2'
    = link_to t('mortgages.common.main'), mortgages_path ,class: 'btn btn-secondary'
  div
    = render 'form', resource: [@mortgage, "Update"]

app/views/mortgages/index.html.slim
div class='mortgages w-100 p-2 d-flex flex-column bg-light'
  div class='text-center border-bottom'
    h2= t('mortgages.index.title_page')
  div class='d-flex justify-content-end mt-2'
    - unless @mortgages.empty?
      = link_to t('mortgages.common.calculate'), new_calculation_path(page: "index"), class: 'btn btn-secondary mx-2 '
    - if can?(:new, Mortgage)
      = link_to t('mortgages.index.new_mortgage'), new_mortgage_path, class: 'btn btn-secondary'
  div
    - if @mortgages
      = render @mortgages

app/views/mortgages/new.html.slim
div class='new-mortgage w-100 bg-light p-2 d-flex flex-column'
  div class='text-center border-bottom'
    h2= t('mortgages.new.title_page')
  div class='d-flex justify-content-end mt-2'
    = link_to t('mortgages.common.main'), mortgages_path ,class: 'btn btn-secondary'
  div
    = render 'form', resource: [@mortgage, "Add"]

app/views/mortgages/show.html.slim
div id="mortgage-#{@mortgage.id}" class='d-flex flex-column w-100 p-2 bg-light'
  div class='mortgage-title text-center'
    h3= @mortgage.title
  div class='mortgage-description px-3 border-bottom'
    h5= @mortgage.description
  
  - if @mortgage.condition&.id != nil
    = render @mortgage.condition
  - else
    div class='d-flex justify-content-end mt-2'
      = link_to t('mortgages.common.main'), mortgages_path ,class: 'btn btn-secondary'   
    - if can?(:new, Condition)
      = render 'conditions/form', resource: [@mortgage, @condition, 'Add']